#!/bin/bash
echo " prime program " 

echo " enter an integer number : "
read n
for ((i=2 ; i<=n/2 ; i++))
do
    if [ $((n%i)) -eq 0 ] 
    then
          echo " your number is not a prime number "
          exit
    fi
done
echo " your number is a prime number "
